work in progress.

diff --git a/src/main/resources/gcpc b/src/main/resources/gcpc
--- a/src/main/resources/gcpc
+++ b/src/main/resources/gcpc
@@ -1,13 +1,20 @@
 #!/bin/bash
 
 DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PARENT_DIR="$(dirname "$DIR")"
 PID_PATH_NAME=/tmp/gcpcn.pid
-SETTINGS_PATH=/etc/default/gcpc
+##################################
+GCP_DIRECTORY=$PARENT_DIR
+GCP_USER=gcpc
+##################################
 VERSION="[[VERSION]]"
 
-if [ ! -f $SETTINGS_PATH ]; then
-   echo "Unable to locate $SETTINGS_PATH configuration file ..."
-   exit 1
+id -u $GCP_USER >/dev/null 2>&1;
+RES=$?
+
+if ["$RES" == "1"] then
+  echo "User $GCP_USER not found!"
+  exit 1
 fi
 
 if [ -z $JAVA_HOME ]; then
@@ -17,14 +24,18 @@ if [ -z $JAVA_HOME ]; then
 fi
 
 echo "Setting environment variables"
-. "$SETTINGS_PATH"
+. "$GCP_DIRECTORY/bin/settings"
+
+if [ ! -d $DATA_DIR ]; then
+  su - $GCP_USER -c "mkdir -p $DATA_DIR"
+fi
 
 function start_service() {
   echo "Starting gcpc service ..."
   PARAMS="-logs_dir $LOGS_DIR -gcp_host $GCP_HOST -data_dir $DATA_DIR -analyze_group $ANALYZE_GROUP_ID -jvm_id $JVM_ID -token $ACCOUNT_TOKEN -https $USE_HTTPS -extension $EXTENSION -reaload_config_ms $RELOAD_CONFIG_MS -sync_files_ms $SYNC_FILES_MS -ttl $TTL"
 
   if [ ! -f $PID_PATH_NAME ]; then
-    su - $USER -c "nohup java $JAVA_PROC_ARGS $PARAMS -Dlogback.configurationFile=$DATA_DIR/logback.xml -jar $DATA_DIR/lib/bootstrap 2>> /dev/null >> /dev/null & echo \$! > $PID_PATH_NAME"
+    su - $GCP_USER -c "nohup java $JAVA_PROC_ARGS $PARAMS -Dlogback.configurationFile=$GCP_DIRECTORY/bin/logback.xml -jar $GCP_DIRECTORY/lib/bs.jar 2>> /dev/null >> /dev/null & echo \$! > $PID_PATH_NAME"
     sleep 5
     echo "gcpc service started."
   else
@@ -34,12 +45,12 @@ function start_service() {
 
 function stop_service() {
   if [ -f $PID_PATH_NAME ]; then
-      PID=$(cat $PID_PATH_NAME);
+      PID=$(su - $GCP_USER -c "cat $PID_PATH_NAME");
       echo "$SERVICE_NAME stoping ..."
       echo "$SERVICE_NAME killing $PID ..."
-      kill $PID;
+      su - $GCP_USER -c "kill $PID"
       echo "$SERVICE_NAME stopped ..."
-      rm -rf $PID_PATH_NAME
+      su - $GCP_USER -c "rm -rf $PID_PATH_NAME"
       sleep 5
   else
       echo "$SERVICE_NAME is not running ..."
@@ -62,7 +73,7 @@ case $1 in
     ;;
     status)
         if [ -f $PID_PATH_NAME ]; then
-          PID=$(cat $PID_PATH_NAME);
+          PID=$(su - $GCP_USER -c "cat $PID_PATH_NAME");
           echo "Started $PID."
         else
           echo "Not started."
