java home corrent detection

diff --git a/src/main/resources/gcpc b/src/main/resources/gcpc
--- a/src/main/resources/gcpc
+++ b/src/main/resources/gcpc
@@ -12,12 +12,6 @@ GCP_USER=gcpc
 VERSION="[[VERSION]]"
 DEBUG=false
 
-if [ -z $JAVA_HOME ]; then
-  echo "Unable to locate Java installation! JAVA_HOME env variable is empty"
-  echo $USAGE_MSG
-  exit 1
-fi
-
 id -u $GCP_USER >/dev/null 2>&1;
 RES=$?
 
@@ -28,6 +22,18 @@ fi
 
 echo "Setting environment variables"
 . "GCP_CONFIG"
+
+if [ -z $JAVA_HOME ]; then
+  if [ -n `which java` ]; then
+    JAVA_CMD=java
+  else
+    echo "Unable to locate Java installation! JAVA_HOME env variable is empty"
+    echo $USAGE_MSG
+    exit 1
+  fi
+else
+  JAVA_CMD=$JAVA_HOME/bin/java
+fi
 
 if [ ! -d $DATA_DIR ]; then
   su - $GCP_USER -c "mkdir -p $DATA_DIR"
@@ -48,11 +54,11 @@ function start_service() {
 
   if $DEBUG ; then
     echo $PARAMS
-    echo "$JAVA_HOME/bin/java $JAVA_PROC_ARGS -Dlogback.configurationFile=$LOGBACK_PATH_NAME -jar $GCP_DIRECTORY/lib/bs.jar $PARAMS"
+    echo "$JAVA_CMD $JAVA_PROC_ARGS -Dlogback.configurationFile=$LOGBACK_PATH_NAME -jar $GCP_DIRECTORY/lib/bs.jar $PARAMS"
   fi
 
   if [ ! -f $PID_PATH_NAME ]; then
-    su - $GCP_USER -c "nohup $JAVA_HOME/bin/java $JAVA_PROC_ARGS -Dlogback.configurationFile=$LOGBACK_PATH_NAME -jar $GCP_DIRECTORY/lib/bs.jar $PARAMS >> /dev/null & echo \$! > $PID_PATH_NAME"
+    su - $GCP_USER -c "nohup $JAVA_CMD $JAVA_PROC_ARGS -Dlogback.configurationFile=$LOGBACK_PATH_NAME -jar $GCP_DIRECTORY/lib/bs.jar $PARAMS >> /dev/null & echo \$! > $PID_PATH_NAME"
     sleep 5
     echo "gcpc service started."
   else
