work in progress.

diff --git a/src/main/resources/gcpc b/src/main/resources/gcpc
--- a/src/main/resources/gcpc
+++ b/src/main/resources/gcpc
@@ -8,18 +8,19 @@ GCP_DIRECTORY=$PARENT_DIR
 GCP_USER=gcpc
 ##################################
 VERSION="[[VERSION]]"
+DEBUG=false
+
+if [ -z $JAVA_HOME ]; then
+  echo "Unable to locate Java installation! JAVA_HOME env variable is empty"
+  echo $USAGE_MSG
+  exit 1
+fi
 
 id -u $GCP_USER >/dev/null 2>&1;
 RES=$?
 
 if ["$RES" == "1"] then
   echo "User $GCP_USER not found!"
-  exit 1
-fi
-
-if [ -z $JAVA_HOME ]; then
-  echo "Unable to locate Java installation! JAVA_HOME env variable is empty"
-  echo $USAGE_MSG
   exit 1
 fi
 
@@ -34,8 +35,12 @@ function start_service() {
   echo "Starting gcpc service ..."
   PARAMS="-logs_dir $LOGS_DIR -gcp_host $GCP_HOST -data_dir $DATA_DIR -analyze_group $ANALYZE_GROUP_ID -jvm_id $JVM_ID -token $ACCOUNT_TOKEN -https $USE_HTTPS -extension $EXTENSION -reaload_config_ms $RELOAD_CONFIG_MS -sync_files_ms $SYNC_FILES_MS -ttl $TTL"
 
+  if $DEBUG ; then
+    echo $PARAMS
+  fi
+
   if [ ! -f $PID_PATH_NAME ]; then
-    su - $GCP_USER -c "nohup java $JAVA_PROC_ARGS $PARAMS -Dlogback.configurationFile=$GCP_DIRECTORY/bin/logback.xml -jar $GCP_DIRECTORY/lib/bs.jar 2>> /dev/null >> /dev/null & echo \$! > $PID_PATH_NAME"
+    su - $GCP_USER -c "nohup $JAVA_HOME/bin/java $JAVA_PROC_ARGS $PARAMS -Dlogback.configurationFile=$GCP_DIRECTORY/bin/logback.xml -jar $GCP_DIRECTORY/lib/bs.jar 2>> /dev/null >> /dev/null & echo \$! > $PID_PATH_NAME"
     sleep 5
     echo "gcpc service started."
   else
